---

- name: kill previously running application
  command: pkill -f "movies-recommender-service-0.1.0.jar"
  ignore_errors: True

- name: clear previous project
  shell: rm -rf {{ recommender_api.home_folder }}

- name: clear logs from previous run
  shell: rm -rf /tmp/logs/movies-recommender-service.log

- name: git checkout
  git: repo=https://github.com/gmiejski/movies-recommender-api.git
       dest={{ recommender_api.home_folder }}
       version="MR-22-performance-tests-aws-simple"

- name: build application
  shell: ./gradlew movies-recommender-service:build -x test chdir={{ recommender_api.home_folder }}

- name: run application
  shell: nohup java -jar -Dneo4j.host={{ neo4j_host }} movies-recommender-service-0.1.0.jar chdir={{ recommender_api.run_folder }} &
