---

- name: build application
  shell: ./gradlew movies-recommender-service:build chdir={{ recommender_api.home_folder }}

- name: run application
  shell: nohup java -jar -Dneo4j.host=localhost -Dspring.profiles-active=metrics movies-recommender-service-0.1.0.jar chdir={{ recommender_api.run_folder }} &
